
GET http://localhost:3000/api/v1/chefs/

###

GET http://localhost:3000/api/v1/chefs/65e8254edd14cbdf1f02f816

###

POST http://localhost:3000/api/v1/chefs
Content-Type: application/json

{
    "name": "Stam",
    "image": "Stam",
    "description": "Stam"
}

###

PATCH  http://localhost:3000/api/v1/chefs/65e86be4202f0131cfb8751b
Content-Type: application/json

{
    "name": "Stam2",
    "image": "Stam2",
    "description": "Stam"
}

###


GET http://localhost:3000/api/v1/chefs/recover/65e71c0347c3df5030428a0e

###
DELETE http://localhost:3000/api/v1/chefs/65e71c0347c3df5030428a0e

